version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-zozo
      dockerfile: Dockerfile
    ports:
      - "5413:80"
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.frontend.rule=Host(`niki-fitness.lorenzocoded.dev`)" # Your domain
    #   - "traefik.http.routers.frontend.entrypoints=websecure" # Or websecure if using HTTPS
    #   - "traefik.http.routers.frontend.tls.certresolver=myresolver" # Your certificate resolver name (configured in Traefik)
    #   - "traefik.http.services.frontend.loadbalancer.server.port=80" # Port your app listens on inside the container
    #   - "traefik.http.middlewares.frontend-spa.forwardregex.regex=^/(?!index\.html|static|.*\.js|.*\.css)(.*)"
    #   - "traefik.http.middlewares.frontend-spa.forwardregex.replacement=/index.html"
    #   - "traefik.http.routers.frontend.middlewares=frontend-spa" # Apply the middleware
    environment:
      - BACKEND_URL=${BACKEND_URL}
    depends_on:
      - backend
    networks:
      - niki-fitness-network

  backend:
    build:
      context: ./backend-hono
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      # Add other environment variables as needed
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - niki-fitness-network
    volumes:
      - ./backend-hono:/app
      - /app/node_modules

networks:
  niki-fitness-network:
    driver: bridge
