version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-zozo
      dockerfile: Dockerfile
    ports:
      - "5413:80"
    environment:
      - BACKEND_URL=${BACKEND_URL}
    depends_on:
      - backend
    networks:
      - niki-fitness-network

  backend:
    build:
      context: ./backend-hono
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      # Add other environment variables as needed
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - niki-fitness-network
    volumes:
      - ./backend-hono:/app
      - /app/node_modules

networks:
  niki-fitness-network:
    driver: bridge
